### ISSUE TITLE
Request/proposal, not an issue

### ISSUE THREAD

**Issue by narbanas22** [DylanCS1/s1_manager#18]
Hi,

Me and my Team really appreciate the work you put into S1_manager tool so first I'd like to say big Thank You!

As a proposal for new functionality, as S1 introduced TAGs, would you consider introducing that functionality as well? Similiar as CI works now but that it assigns TAGs to machines. Logic would be to first create the TAG in the console or through API and then use it in S1_manager.

**Comment by DylanCS1** [comment]
Thank you for the feedback. Yes, absolutely. This is something I hope to have added in soon.

**Comment by DylanCS1** [comment]
The ability to export Endpoint Tag details to CSV and to Add/Remove Endpoint Tags from Agents has been added to the 2022.0.3 release.
